import type { CSSFileOutput } from "@sugarcube-sh/core";
import packageJson from "../package.json" with { type: "json" };

const CSS_BANNER = `/* Generated by @sugarcube-sh/cli v${packageJson.version} */\n\n`;

export function addBanner(output: CSSFileOutput): CSSFileOutput {
    return output.map((file) => ({
        ...file,
        css: CSS_BANNER + file.css,
    }));
}

export function wrapInLayer(output: CSSFileOutput, layerName: string): CSSFileOutput {
    return output.map((file) => {
        // Need extra formatting for @layer blocks
        const indentedCss = file.css
            .split("\n")
            .map((line) => (line.trim() ? `    ${line}` : line))
            .join("\n");
        return {
            ...file,
            css: `@layer ${layerName} {\n${indentedCss}}\n`,
        };
    });
}
