import type { CSSFileOutput, InternalConfig } from "@sugarcube-sh/core";
import type { UnoGenerator } from "@unocss/core";
import packageJson from "../package.json" with { type: "json" };
import { getMarkupFiles, readMarkupSources } from "./scan-markup.js";

const CSS_BANNER = `/* Generated by @sugarcube-sh/cli v${packageJson.version} */\n\n`;

export function addBanner(output: CSSFileOutput): CSSFileOutput {
    return output.map((file) => ({
        ...file,
        css: CSS_BANNER + file.css,
    }));
}

export function wrapInLayer(output: CSSFileOutput, layerName: string): CSSFileOutput {
    return output.map((file) => {
        // Need extra formatting for @layer blocks
        const indentedCss = file.css
            .split("\n")
            .map((line) => (line.trim() ? `    ${line}` : line))
            .join("\n");
        return {
            ...file,
            css: `@layer ${layerName} {\n${indentedCss}}\n`,
        };
    });
}

export async function utilitiesFromMarkup(
    generator: UnoGenerator,
    safelist: string[],
    config: InternalConfig,
): Promise<CSSFileOutput> {
    const files = await getMarkupFiles(config.content);
    if (files.length === 0 && safelist.length === 0) return [];

    const sources = await readMarkupSources(files);
    const { css } = await generator.generate(sources.join("\n"), { preflights: false });
    if (!css?.trim()) return [];

    return [
        {
            path: config.utilities.path,
            css,
        },
    ];
}
