import {
    type CSSFileOutput,
    assignCSSNames,
    clearMatchCache,
    convertConfigToUnoRules,
    enumerateSafelistClasses,
    generateCSSVariables,
    groupByContext,
    writeCSSUtilitiesToDisk,
    writeCSSVariablesToDisk,
} from "@sugarcube-sh/core";
import type { InternalConfig, NormalizedRenderableTokens, Permutation } from "@sugarcube-sh/core";
import { type UserConfig, createGenerator } from "@unocss/core";
import packageJson from "../../package.json" with { type: "json" };
import { prepareTokens } from "../prepare-tokens.js";
import { getMarkupFiles, readMarkupSources } from "../scan-markup.js";

const CSS_BANNER = `/* Generated by @sugarcube-sh/cli v${packageJson.version} */\n\n`;

export interface GenerateAllCSSOptions {
    variablesOnly?: boolean;
    utilitiesOnly?: boolean;
}

export type GenerationResult = {
    output: CSSFileOutput;
    warnings: Array<{ path: string; message: string }>;
};

export type ChangeKind = "token" | "markup";

export interface WatchSession {
    /** Cold build: full token pipeline + variables + utilities. Warms the cache. */
    primeAndBuild(): Promise<GenerationResult>;
    /** Regenerate in response to a watched change, routed by `kind`. */
    onChange(kind: ChangeKind, changedPath: string): Promise<GenerationResult>;
}

async function generateSugarcubeUtilities(
    tokens: NormalizedRenderableTokens,
    config: InternalConfig,
): Promise<CSSFileOutput> {
    if (!config.utilities.classes || Object.keys(config.utilities.classes).length === 0) {
        return [];
    }

    const safelist = enumerateSafelistClasses(config.utilities.classes, tokens);

    const sugarcubePreset = {
        name: "sugarcube",
        rules: convertConfigToUnoRules(config.utilities.classes, tokens),
        preflights: [],
    };

    const generatorOptions: UserConfig = {
        presets: [sugarcubePreset],
        safelist,
    };

    const generator = await createGenerator(generatorOptions);

    const files = await getMarkupFiles(config.content);
    if (files.length === 0 && safelist.length === 0) return [];

    const sources = await readMarkupSources(files);
    const combinedSource = sources.join("\n");

    const { css } = await generator.generate(combinedSource, { preflights: false });
    if (!css?.trim()) return [];

    return [
        {
            path: config.utilities.path,
            css,
        },
    ];
}

function addBanner(output: CSSFileOutput): CSSFileOutput {
    return output.map((file) => ({
        ...file,
        css: CSS_BANNER + file.css,
    }));
}

function wrapInLayer(output: CSSFileOutput, layerName: string): CSSFileOutput {
    return output.map((file) => {
        // Need extra formatting for @layer blocks
        const indentedCss = file.css
            .split("\n")
            .map((line) => (line.trim() ? `    ${line}` : line))
            .join("\n");
        return {
            ...file,
            css: `@layer ${layerName} {\n${indentedCss}}\n`,
        };
    });
}

async function writeVariables(
    convertedTokens: NormalizedRenderableTokens,
    config: InternalConfig,
    permutations: Permutation[],
): Promise<CSSFileOutput> {
    let cssVariables = await generateCSSVariables(convertedTokens, config, permutations);
    if (config.variables.layer) {
        cssVariables = wrapInLayer(cssVariables, config.variables.layer);
    }
    const cssVariablesWithBanner = addBanner(cssVariables);
    await writeCSSVariablesToDisk(cssVariablesWithBanner);
    return cssVariablesWithBanner;
}

async function writeUtilities(
    convertedTokens: NormalizedRenderableTokens,
    config: InternalConfig,
): Promise<CSSFileOutput> {
    let utilities = await generateSugarcubeUtilities(convertedTokens, config);
    if (config.utilities.layer) {
        utilities = wrapInLayer(utilities, config.utilities.layer);
    }
    const utilitiesWithBanner = addBanner(utilities);
    await writeCSSUtilitiesToDisk(utilitiesWithBanner);
    return utilitiesWithBanner;
}

/** Cached results of the token pipeline — everything a markup change can reuse. */
type TokenState = {
    convertedTokens: NormalizedRenderableTokens;
    permutations: Permutation[];
    warnings: GenerationResult["warnings"];
};

/**
 * A watch session holds the token-pipeline results between events so it can
 * route regeneration by what changed:
 *
 * - token change → fully reload + resolve + convert from disk, then regenerate
 *   variables and utilities. Nothing stale is reused.
 * - markup change → reuse the cached token state verbatim and regenerate only
 *   utilities (variables don't depend on markup), skipping the entire token
 *   pipeline. Each concern is always fully recomputed, never patched, so the
 *   output matches a cold build.
 *
 * The utility generator is rebuilt on every utilities pass rather than persisted
 * because UnoCSS orders rules by first-seen token, so a persisted generator
 * could emit utilities in a different order than a cold build once a markup edit
 * introduces a new class.
 */
export function createWatchSession(
    config: InternalConfig,
    options: GenerateAllCSSOptions = {},
): WatchSession {
    let state: TokenState | null = null;

    async function reloadTokens(): Promise<TokenState> {
        clearMatchCache();
        const { trees, resolved, warnings, permutations } = await prepareTokens(config);
        const next: TokenState = {
            convertedTokens: assignCSSNames(groupByContext(trees, resolved), config),
            permutations,
            warnings,
        };
        state = next;
        return next;
    }

    async function buildAll(current: TokenState): Promise<CSSFileOutput> {
        const output: CSSFileOutput = [];
        if (!options.utilitiesOnly) {
            output.push(
                ...(await writeVariables(current.convertedTokens, config, current.permutations)),
            );
        }
        if (!options.variablesOnly) {
            output.push(...(await writeUtilities(current.convertedTokens, config)));
        }
        return output;
    }

    return {
        async primeAndBuild() {
            const current = await reloadTokens();
            return { output: await buildAll(current), warnings: current.warnings };
        },
        async onChange(kind, _changedPath) {
            if (kind === "token" || state === null) {
                const current = await reloadTokens();
                return { output: await buildAll(current), warnings: current.warnings };
            }

            const output = options.variablesOnly
                ? []
                : await writeUtilities(state.convertedTokens, config);
            return { output, warnings: state.warnings };
        },
    };
}

export function runFullGeneration(
    config: InternalConfig,
    options: GenerateAllCSSOptions = {},
): Promise<GenerationResult> {
    return createWatchSession(config, options).primeAndBuild();
}
