import {
    type CSSFileOutput,
    assignCSSNames,
    clearMatchCache,
    convertConfigToUnoRules,
    enumerateSafelistClasses,
    generateCSSVariables,
    groupByContext,
    writeCSSUtilitiesToDisk,
    writeCSSVariablesToDisk,
} from "@sugarcube-sh/core";
import type {
    InternalConfig,
    NormalizedRenderableTokens,
    Permutation,
    ResolvedTokens,
    TokenTree,
} from "@sugarcube-sh/core";
import { type UserConfig, createGenerator } from "@unocss/core";
import packageJson from "../../package.json" with { type: "json" };
import { prepareTokens } from "../prepare-tokens.js";
import { getMarkupFiles, readMarkupSources } from "../scan-markup.js";

const CSS_BANNER = `/* Generated by @sugarcube-sh/cli v${packageJson.version} */\n\n`;

export interface GenerateAllCSSOptions {
    variablesOnly?: boolean;
    utilitiesOnly?: boolean;
}

export type GenerationResult = {
    output: CSSFileOutput;
    warnings: Array<{ path: string; message: string }>;
};

/** Which watcher emitted the event. Phase 0 ignores it; later phases route on it. */
export type ChangeKind = "token" | "markup";

export interface WatchSession {
    /** Initial cold build. Also the place later phases will warm caches. */
    primeAndBuild(): Promise<GenerationResult>;
    /** Regenerate in response to a watched change. */
    onChange(kind: ChangeKind, changedPath: string): Promise<GenerationResult>;
}

async function generateSugarcubeUtilities(
    tokens: NormalizedRenderableTokens,
    config: InternalConfig,
): Promise<CSSFileOutput> {
    if (!config.utilities.classes || Object.keys(config.utilities.classes).length === 0) {
        return [];
    }

    const safelist = enumerateSafelistClasses(config.utilities.classes, tokens);

    const sugarcubePreset = {
        name: "sugarcube",
        rules: convertConfigToUnoRules(config.utilities.classes, tokens),
        preflights: [],
    };

    const generatorOptions: UserConfig = {
        presets: [sugarcubePreset],
        safelist,
    };

    const generator = await createGenerator(generatorOptions);

    const files = await getMarkupFiles(config.content);
    if (files.length === 0 && safelist.length === 0) return [];

    const sources = await readMarkupSources(files);
    const combinedSource = sources.join("\n");

    const { css } = await generator.generate(combinedSource, { preflights: false });
    if (!css?.trim()) return [];

    return [
        {
            path: config.utilities.path,
            css,
        },
    ];
}

function addBanner(output: CSSFileOutput): CSSFileOutput {
    return output.map((file) => ({
        ...file,
        css: CSS_BANNER + file.css,
    }));
}

function wrapInLayer(output: CSSFileOutput, layerName: string): CSSFileOutput {
    return output.map((file) => {
        // Need extra formatting for @layer blocks
        const indentedCss = file.css
            .split("\n")
            .map((line) => (line.trim() ? `    ${line}` : line))
            .join("\n");
        return {
            ...file,
            css: `@layer ${layerName} {\n${indentedCss}}\n`,
        };
    });
}

async function generateAllCSS(
    trees: TokenTree[],
    resolved: ResolvedTokens,
    config: InternalConfig,
    permutations: Permutation[],
    options: GenerateAllCSSOptions = {},
): Promise<CSSFileOutput> {
    const output: CSSFileOutput = [];

    const convertedTokens = assignCSSNames(groupByContext(trees, resolved), config);

    if (!options.utilitiesOnly) {
        let cssVariables = await generateCSSVariables(convertedTokens, config, permutations);
        if (config.variables.layer) {
            cssVariables = wrapInLayer(cssVariables, config.variables.layer);
        }
        const cssVariablesWithBanner = addBanner(cssVariables);
        await writeCSSVariablesToDisk(cssVariablesWithBanner);
        output.push(...cssVariablesWithBanner);
    }

    if (!options.variablesOnly) {
        let utilities = await generateSugarcubeUtilities(convertedTokens, config);
        if (config.utilities.layer) {
            utilities = wrapInLayer(utilities, config.utilities.layer);
        }
        const utilitiesWithBanner = addBanner(utilities);
        await writeCSSUtilitiesToDisk(utilitiesWithBanner);
        output.push(...utilitiesWithBanner);
    }

    return output;
}

async function runGeneration(
    config: InternalConfig,
    options: GenerateAllCSSOptions = {},
): Promise<GenerationResult> {
    clearMatchCache();
    const { trees, resolved, warnings, permutations } = await prepareTokens(config);
    const output = await generateAllCSS(trees, resolved, config, permutations, options);
    return { output, warnings };
}

/**
 * One-shot generation used by the non-watch path. Shares the same mechanics as
 * a watch session's cold build so the two can't drift.
 */
export function runFullGeneration(
    config: InternalConfig,
    options: GenerateAllCSSOptions = {},
): Promise<GenerationResult> {
    return runGeneration(config, options);
}

/**
 * A watch session holds the state that will let later phases regenerate
 * incrementally. In Phase 0 it holds nothing: every event is a full rebuild,
 * matching the pre-extraction behaviour exactly. The `kind` argument is the
 * seam that Fix A (routing by token-vs-markup change) will build on.
 */
export function createWatchSession(
    config: InternalConfig,
    options: GenerateAllCSSOptions = {},
): WatchSession {
    return {
        primeAndBuild: () => runGeneration(config, options),
        onChange: (_kind, _changedPath) => runGeneration(config, options),
    };
}
